### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by gsnewmark** [do-pump/do-pump#7]
It looks like `python-digitalocean` library [uses GPLv3 license](https://github.com/koalalorenzo/python-digitalocean/blob/master/LICENSE.txt), which means we can only use the same (or possibly some variant of it).

Should we switch to other API wrapper/create our own in order to choose a more permissive license or GPLv3 is ok?

[Short GPLv3 explanation](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3))

**Comment by goldobin** [comment]
For me it looks good. Have no any objections on it.

**Comment by gsnewmark** [comment]
If i understand correctly it's a bit virus-like, so our tool couldn't be embedded into the proprietary products. Not sure we ever need to embed it though.

**Comment by gsnewmark** [comment]
Another question is whether [click's license](https://github.com/mitsuhiko/click/blob/master/LICENSE) is compatible with GPLv3.
